services:
  nest:
    image: nest:1.0.0
    expose:
      - 3000
    volumes:
      - /data/www/nest/runtime/:/app/runtime
    restart: unless-stopped
    networks:
      - nest-network
      - common-network

networks:
  nest-network:
    external: true
    name: nest-network

  common-network:
    external: true
