services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nest:dev
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: debug
    volumes:
      - D:\data\nest\runtime:/app/runtime
    restart: unless-stopped
    networks:
      - default
      - common-network

networks:
  default:
    external: true
    name: nest-network

  common-network:
    external: true
