services:

  nest:
    image: nest:latest
    expose:
      - 3000
    volumes:
      - D:\data\nest\runtime:/app/runtime
    restart: unless-stopped

    networks:
      - default
      - common-network

networks:
  default:
    external: true
    name: nest-network

  common-network:
    external: true