services:

  nest-api:
    image: golang:1.26.3-trixie

    working_dir: /app
    expose:
      - 3000
    volumes:
      - ./:/app
      - /app/.git

    environment:
      TZ: Asia/Shanghai

      APP_ENV: local
      GIN_MODE: debug

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123123
      DB_NAME: nest

      JWT_SECRET: JWT_SECRET

      REDIS_HOST: valkey
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_DB: 0

    # 配置过多再引入 env_file
    command: go run cmd/api/main.go

    networks:
      - default
      - common-network

networks:
  default:
    external: true
    name: nest-network

  common-network:
    external: true