// Code generated by ent, DO NOT EDIT.

package projectshareinterface

import (
	"nest-api/internal/ent/predicate"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldLTE(FieldID, id))
}

// ShareID applies equality check predicate on the "share_id" field. It's identical to ShareIDEQ.
func ShareID(v int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldShareID, v))
}

// InterfaceID applies equality check predicate on the "interface_id" field. It's identical to InterfaceIDEQ.
func InterfaceID(v int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldInterfaceID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldCreatedAt, v))
}

// ShareIDEQ applies the EQ predicate on the "share_id" field.
func ShareIDEQ(v int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldShareID, v))
}

// ShareIDNEQ applies the NEQ predicate on the "share_id" field.
func ShareIDNEQ(v int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNEQ(FieldShareID, v))
}

// ShareIDIn applies the In predicate on the "share_id" field.
func ShareIDIn(vs ...int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldIn(FieldShareID, vs...))
}

// ShareIDNotIn applies the NotIn predicate on the "share_id" field.
func ShareIDNotIn(vs ...int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNotIn(FieldShareID, vs...))
}

// InterfaceIDEQ applies the EQ predicate on the "interface_id" field.
func InterfaceIDEQ(v int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldInterfaceID, v))
}

// InterfaceIDNEQ applies the NEQ predicate on the "interface_id" field.
func InterfaceIDNEQ(v int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNEQ(FieldInterfaceID, v))
}

// InterfaceIDIn applies the In predicate on the "interface_id" field.
func InterfaceIDIn(vs ...int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldIn(FieldInterfaceID, vs...))
}

// InterfaceIDNotIn applies the NotIn predicate on the "interface_id" field.
func InterfaceIDNotIn(vs ...int64) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNotIn(FieldInterfaceID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v utils.DateTime) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.FieldLTE(FieldCreatedAt, v))
}

// HasShare applies the HasEdge predicate on the "share" edge.
func HasShare() predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShareTable, ShareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShareWith applies the HasEdge predicate on the "share" edge with a given conditions (other predicates).
func HasShareWith(preds ...predicate.ProjectShare) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(func(s *sql.Selector) {
		step := newShareStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInterface applies the HasEdge predicate on the "interface" edge.
func HasInterface() predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InterfaceTable, InterfaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInterfaceWith applies the HasEdge predicate on the "interface" edge with a given conditions (other predicates).
func HasInterfaceWith(preds ...predicate.API) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(func(s *sql.Selector) {
		step := newInterfaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectShareInterface) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectShareInterface) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectShareInterface) predicate.ProjectShareInterface {
	return predicate.ProjectShareInterface(sql.NotPredicates(p))
}
