// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nest-api/internal/ent/api"
	"nest-api/internal/ent/folder"
	"nest-api/internal/ent/project"
	"nest-api/internal/ent/user"
	"nest-api/internal/utils"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// API is the model entity for the API schema.
type API struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID int64 `json:"id,omitempty"`
	// 项目 ID
	ProjectID int64 `json:"project_id,omitempty"`
	// 所属文件夹 ID
	FolderID int64 `json:"folder_id,omitempty"`
	// 接口名称
	Name string `json:"name,omitempty"`
	// HTTP 方法
	Method string `json:"method,omitempty"`
	// 接口路径
	URL string `json:"url,omitempty"`
	// 状态：1: 已发布, 2: 测试中, 3: 开发中, 4: 异常, 5: 维护, 6: 废弃
	Status uint8 `json:"status,omitempty"`
	// 请求体格式：form-data, json, xml, raw, binary
	RequestBodyFormat string `json:"request_body_format,omitempty"`
	// 请求体数据类型
	RequestBodyDataType string `json:"request_body_data_type,omitempty"`
	// Raw 请求体内容
	RequestBodyRaw string `json:"request_body_raw,omitempty"`
	// 排序
	SortOrder int `json:"sort_order,omitempty"`
	// 创建者用户 ID
	CreatedBy int64 `json:"created_by,omitempty"`
	// 最后修改者用户 ID
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// 创建时间
	CreatedAt utils.DateTime `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt utils.DateTime `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *utils.DateTime `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the APIQuery when eager-loading is set.
	Edges        APIEdges `json:"edges"`
	selectValues sql.SelectValues
}

// APIEdges holds the relations/edges for other nodes in the graph.
type APIEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Folder holds the value of the folder edge.
	Folder *Folder `json:"folder,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Updater holds the value of the updater edge.
	Updater *User `json:"updater,omitempty"`
	// ResponseHeaders holds the value of the response_headers edge.
	ResponseHeaders []*InterfaceHeader `json:"response_headers,omitempty"`
	// ResponseResults holds the value of the response_results edge.
	ResponseResults []*InterfaceResult `json:"response_results,omitempty"`
	// ResponseExamples holds the value of the response_examples edge.
	ResponseExamples []*InterfaceExample `json:"response_examples,omitempty"`
	// RequestHeaders holds the value of the request_headers edge.
	RequestHeaders []*InterfaceRequestHeader `json:"request_headers,omitempty"`
	// QueryParams holds the value of the query_params edge.
	QueryParams []*InterfaceQueryParam `json:"query_params,omitempty"`
	// BodyFields holds the value of the body_fields edge.
	BodyFields []*InterfaceBodyField `json:"body_fields,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [10]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// FolderOrErr returns the Folder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIEdges) FolderOrErr() (*Folder, error) {
	if e.Folder != nil {
		return e.Folder, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: folder.Label}
	}
	return nil, &NotLoadedError{edge: "folder"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// UpdaterOrErr returns the Updater value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIEdges) UpdaterOrErr() (*User, error) {
	if e.Updater != nil {
		return e.Updater, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "updater"}
}

// ResponseHeadersOrErr returns the ResponseHeaders value or an error if the edge
// was not loaded in eager-loading.
func (e APIEdges) ResponseHeadersOrErr() ([]*InterfaceHeader, error) {
	if e.loadedTypes[4] {
		return e.ResponseHeaders, nil
	}
	return nil, &NotLoadedError{edge: "response_headers"}
}

// ResponseResultsOrErr returns the ResponseResults value or an error if the edge
// was not loaded in eager-loading.
func (e APIEdges) ResponseResultsOrErr() ([]*InterfaceResult, error) {
	if e.loadedTypes[5] {
		return e.ResponseResults, nil
	}
	return nil, &NotLoadedError{edge: "response_results"}
}

// ResponseExamplesOrErr returns the ResponseExamples value or an error if the edge
// was not loaded in eager-loading.
func (e APIEdges) ResponseExamplesOrErr() ([]*InterfaceExample, error) {
	if e.loadedTypes[6] {
		return e.ResponseExamples, nil
	}
	return nil, &NotLoadedError{edge: "response_examples"}
}

// RequestHeadersOrErr returns the RequestHeaders value or an error if the edge
// was not loaded in eager-loading.
func (e APIEdges) RequestHeadersOrErr() ([]*InterfaceRequestHeader, error) {
	if e.loadedTypes[7] {
		return e.RequestHeaders, nil
	}
	return nil, &NotLoadedError{edge: "request_headers"}
}

// QueryParamsOrErr returns the QueryParams value or an error if the edge
// was not loaded in eager-loading.
func (e APIEdges) QueryParamsOrErr() ([]*InterfaceQueryParam, error) {
	if e.loadedTypes[8] {
		return e.QueryParams, nil
	}
	return nil, &NotLoadedError{edge: "query_params"}
}

// BodyFieldsOrErr returns the BodyFields value or an error if the edge
// was not loaded in eager-loading.
func (e APIEdges) BodyFieldsOrErr() ([]*InterfaceBodyField, error) {
	if e.loadedTypes[9] {
		return e.BodyFields, nil
	}
	return nil, &NotLoadedError{edge: "body_fields"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*API) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case api.FieldDeletedAt:
			values[i] = &sql.NullScanner{S: new(utils.DateTime)}
		case api.FieldID, api.FieldProjectID, api.FieldFolderID, api.FieldStatus, api.FieldSortOrder, api.FieldCreatedBy, api.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case api.FieldName, api.FieldMethod, api.FieldURL, api.FieldRequestBodyFormat, api.FieldRequestBodyDataType, api.FieldRequestBodyRaw:
			values[i] = new(sql.NullString)
		case api.FieldCreatedAt, api.FieldUpdatedAt:
			values[i] = new(utils.DateTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the API fields.
func (_m *API) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case api.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case api.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.Int64
			}
		case api.FieldFolderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field folder_id", values[i])
			} else if value.Valid {
				_m.FolderID = value.Int64
			}
		case api.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case api.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case api.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case api.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case api.FieldRequestBodyFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_format", values[i])
			} else if value.Valid {
				_m.RequestBodyFormat = value.String
			}
		case api.FieldRequestBodyDataType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_data_type", values[i])
			} else if value.Valid {
				_m.RequestBodyDataType = value.String
			}
		case api.FieldRequestBodyRaw:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_raw", values[i])
			} else if value.Valid {
				_m.RequestBodyRaw = value.String
			}
		case api.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case api.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case api.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case api.FieldCreatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil {
				_m.CreatedAt = *value
			}
		case api.FieldUpdatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value != nil {
				_m.UpdatedAt = *value
			}
		case api.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(utils.DateTime)
				*_m.DeletedAt = *value.S.(*utils.DateTime)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the API.
// This includes values selected through modifiers, order, etc.
func (_m *API) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the API entity.
func (_m *API) QueryProject() *ProjectQuery {
	return NewAPIClient(_m.config).QueryProject(_m)
}

// QueryFolder queries the "folder" edge of the API entity.
func (_m *API) QueryFolder() *FolderQuery {
	return NewAPIClient(_m.config).QueryFolder(_m)
}

// QueryCreator queries the "creator" edge of the API entity.
func (_m *API) QueryCreator() *UserQuery {
	return NewAPIClient(_m.config).QueryCreator(_m)
}

// QueryUpdater queries the "updater" edge of the API entity.
func (_m *API) QueryUpdater() *UserQuery {
	return NewAPIClient(_m.config).QueryUpdater(_m)
}

// QueryResponseHeaders queries the "response_headers" edge of the API entity.
func (_m *API) QueryResponseHeaders() *InterfaceHeaderQuery {
	return NewAPIClient(_m.config).QueryResponseHeaders(_m)
}

// QueryResponseResults queries the "response_results" edge of the API entity.
func (_m *API) QueryResponseResults() *InterfaceResultQuery {
	return NewAPIClient(_m.config).QueryResponseResults(_m)
}

// QueryResponseExamples queries the "response_examples" edge of the API entity.
func (_m *API) QueryResponseExamples() *InterfaceExampleQuery {
	return NewAPIClient(_m.config).QueryResponseExamples(_m)
}

// QueryRequestHeaders queries the "request_headers" edge of the API entity.
func (_m *API) QueryRequestHeaders() *InterfaceRequestHeaderQuery {
	return NewAPIClient(_m.config).QueryRequestHeaders(_m)
}

// QueryQueryParams queries the "query_params" edge of the API entity.
func (_m *API) QueryQueryParams() *InterfaceQueryParamQuery {
	return NewAPIClient(_m.config).QueryQueryParams(_m)
}

// QueryBodyFields queries the "body_fields" edge of the API entity.
func (_m *API) QueryBodyFields() *InterfaceBodyFieldQuery {
	return NewAPIClient(_m.config).QueryBodyFields(_m)
}

// Update returns a builder for updating this API.
// Note that you need to call API.Unwrap() before calling this method if this API
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *API) Update() *APIUpdateOne {
	return NewAPIClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the API entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *API) Unwrap() *API {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: API is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *API) String() string {
	var builder strings.Builder
	builder.WriteString("API(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("folder_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FolderID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("request_body_format=")
	builder.WriteString(_m.RequestBodyFormat)
	builder.WriteString(", ")
	builder.WriteString("request_body_data_type=")
	builder.WriteString(_m.RequestBodyDataType)
	builder.WriteString(", ")
	builder.WriteString("request_body_raw=")
	builder.WriteString(_m.RequestBodyRaw)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// APIs is a parsable slice of API.
type APIs []*API
