// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nest-api/internal/ent/api"
	"nest-api/internal/ent/folder"
	"nest-api/internal/ent/interfacebodyfield"
	"nest-api/internal/ent/interfaceexample"
	"nest-api/internal/ent/interfaceheader"
	"nest-api/internal/ent/interfacequeryparam"
	"nest-api/internal/ent/interfacerequestheader"
	"nest-api/internal/ent/interfaceresult"
	"nest-api/internal/ent/predicate"
	"nest-api/internal/ent/project"
	"nest-api/internal/ent/user"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// APIUpdate is the builder for updating API entities.
type APIUpdate struct {
	config
	hooks    []Hook
	mutation *APIMutation
}

// Where appends a list predicates to the APIUpdate builder.
func (_u *APIUpdate) Where(ps ...predicate.API) *APIUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *APIUpdate) SetProjectID(v int64) *APIUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *APIUpdate) SetNillableProjectID(v *int64) *APIUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *APIUpdate) SetFolderID(v int64) *APIUpdate {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *APIUpdate) SetNillableFolderID(v *int64) *APIUpdate {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *APIUpdate) SetName(v string) *APIUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIUpdate) SetNillableName(v *string) *APIUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *APIUpdate) SetMethod(v string) *APIUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *APIUpdate) SetNillableMethod(v *string) *APIUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *APIUpdate) SetURL(v string) *APIUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *APIUpdate) SetNillableURL(v *string) *APIUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *APIUpdate) SetStatus(v uint8) *APIUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *APIUpdate) SetNillableStatus(v *uint8) *APIUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *APIUpdate) AddStatus(v int8) *APIUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetRequestBodyFormat sets the "request_body_format" field.
func (_u *APIUpdate) SetRequestBodyFormat(v string) *APIUpdate {
	_u.mutation.SetRequestBodyFormat(v)
	return _u
}

// SetNillableRequestBodyFormat sets the "request_body_format" field if the given value is not nil.
func (_u *APIUpdate) SetNillableRequestBodyFormat(v *string) *APIUpdate {
	if v != nil {
		_u.SetRequestBodyFormat(*v)
	}
	return _u
}

// SetRequestBodyDataType sets the "request_body_data_type" field.
func (_u *APIUpdate) SetRequestBodyDataType(v string) *APIUpdate {
	_u.mutation.SetRequestBodyDataType(v)
	return _u
}

// SetNillableRequestBodyDataType sets the "request_body_data_type" field if the given value is not nil.
func (_u *APIUpdate) SetNillableRequestBodyDataType(v *string) *APIUpdate {
	if v != nil {
		_u.SetRequestBodyDataType(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *APIUpdate) SetSortOrder(v int) *APIUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *APIUpdate) SetNillableSortOrder(v *int) *APIUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *APIUpdate) AddSortOrder(v int) *APIUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *APIUpdate) SetCreatedBy(v int64) *APIUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *APIUpdate) SetNillableCreatedBy(v *int64) *APIUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *APIUpdate) SetUpdatedBy(v int64) *APIUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *APIUpdate) SetNillableUpdatedBy(v *int64) *APIUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *APIUpdate) SetCreatedAt(v utils.DateTime) *APIUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *APIUpdate) SetNillableCreatedAt(v *utils.DateTime) *APIUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIUpdate) SetUpdatedAt(v utils.DateTime) *APIUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIUpdate) SetDeletedAt(v utils.DateTime) *APIUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIUpdate) SetNillableDeletedAt(v *utils.DateTime) *APIUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *APIUpdate) ClearDeletedAt() *APIUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *APIUpdate) SetProject(v *Project) *APIUpdate {
	return _u.SetProjectID(v.ID)
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *APIUpdate) SetFolder(v *Folder) *APIUpdate {
	return _u.SetFolderID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *APIUpdate) SetCreatorID(id int64) *APIUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *APIUpdate) SetCreator(v *User) *APIUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *APIUpdate) SetUpdaterID(id int64) *APIUpdate {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *APIUpdate) SetUpdater(v *User) *APIUpdate {
	return _u.SetUpdaterID(v.ID)
}

// AddResponseHeaderIDs adds the "response_headers" edge to the InterfaceHeader entity by IDs.
func (_u *APIUpdate) AddResponseHeaderIDs(ids ...int64) *APIUpdate {
	_u.mutation.AddResponseHeaderIDs(ids...)
	return _u
}

// AddResponseHeaders adds the "response_headers" edges to the InterfaceHeader entity.
func (_u *APIUpdate) AddResponseHeaders(v ...*InterfaceHeader) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseHeaderIDs(ids...)
}

// AddResponseResultIDs adds the "response_results" edge to the InterfaceResult entity by IDs.
func (_u *APIUpdate) AddResponseResultIDs(ids ...int64) *APIUpdate {
	_u.mutation.AddResponseResultIDs(ids...)
	return _u
}

// AddResponseResults adds the "response_results" edges to the InterfaceResult entity.
func (_u *APIUpdate) AddResponseResults(v ...*InterfaceResult) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseResultIDs(ids...)
}

// AddResponseExampleIDs adds the "response_examples" edge to the InterfaceExample entity by IDs.
func (_u *APIUpdate) AddResponseExampleIDs(ids ...int64) *APIUpdate {
	_u.mutation.AddResponseExampleIDs(ids...)
	return _u
}

// AddResponseExamples adds the "response_examples" edges to the InterfaceExample entity.
func (_u *APIUpdate) AddResponseExamples(v ...*InterfaceExample) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseExampleIDs(ids...)
}

// AddRequestHeaderIDs adds the "request_headers" edge to the InterfaceRequestHeader entity by IDs.
func (_u *APIUpdate) AddRequestHeaderIDs(ids ...int64) *APIUpdate {
	_u.mutation.AddRequestHeaderIDs(ids...)
	return _u
}

// AddRequestHeaders adds the "request_headers" edges to the InterfaceRequestHeader entity.
func (_u *APIUpdate) AddRequestHeaders(v ...*InterfaceRequestHeader) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestHeaderIDs(ids...)
}

// AddQueryParamIDs adds the "query_params" edge to the InterfaceQueryParam entity by IDs.
func (_u *APIUpdate) AddQueryParamIDs(ids ...int64) *APIUpdate {
	_u.mutation.AddQueryParamIDs(ids...)
	return _u
}

// AddQueryParams adds the "query_params" edges to the InterfaceQueryParam entity.
func (_u *APIUpdate) AddQueryParams(v ...*InterfaceQueryParam) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQueryParamIDs(ids...)
}

// AddBodyFieldIDs adds the "body_fields" edge to the InterfaceBodyField entity by IDs.
func (_u *APIUpdate) AddBodyFieldIDs(ids ...int64) *APIUpdate {
	_u.mutation.AddBodyFieldIDs(ids...)
	return _u
}

// AddBodyFields adds the "body_fields" edges to the InterfaceBodyField entity.
func (_u *APIUpdate) AddBodyFields(v ...*InterfaceBodyField) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBodyFieldIDs(ids...)
}

// Mutation returns the APIMutation object of the builder.
func (_u *APIUpdate) Mutation() *APIMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *APIUpdate) ClearProject() *APIUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *APIUpdate) ClearFolder() *APIUpdate {
	_u.mutation.ClearFolder()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *APIUpdate) ClearCreator() *APIUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *APIUpdate) ClearUpdater() *APIUpdate {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearResponseHeaders clears all "response_headers" edges to the InterfaceHeader entity.
func (_u *APIUpdate) ClearResponseHeaders() *APIUpdate {
	_u.mutation.ClearResponseHeaders()
	return _u
}

// RemoveResponseHeaderIDs removes the "response_headers" edge to InterfaceHeader entities by IDs.
func (_u *APIUpdate) RemoveResponseHeaderIDs(ids ...int64) *APIUpdate {
	_u.mutation.RemoveResponseHeaderIDs(ids...)
	return _u
}

// RemoveResponseHeaders removes "response_headers" edges to InterfaceHeader entities.
func (_u *APIUpdate) RemoveResponseHeaders(v ...*InterfaceHeader) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseHeaderIDs(ids...)
}

// ClearResponseResults clears all "response_results" edges to the InterfaceResult entity.
func (_u *APIUpdate) ClearResponseResults() *APIUpdate {
	_u.mutation.ClearResponseResults()
	return _u
}

// RemoveResponseResultIDs removes the "response_results" edge to InterfaceResult entities by IDs.
func (_u *APIUpdate) RemoveResponseResultIDs(ids ...int64) *APIUpdate {
	_u.mutation.RemoveResponseResultIDs(ids...)
	return _u
}

// RemoveResponseResults removes "response_results" edges to InterfaceResult entities.
func (_u *APIUpdate) RemoveResponseResults(v ...*InterfaceResult) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseResultIDs(ids...)
}

// ClearResponseExamples clears all "response_examples" edges to the InterfaceExample entity.
func (_u *APIUpdate) ClearResponseExamples() *APIUpdate {
	_u.mutation.ClearResponseExamples()
	return _u
}

// RemoveResponseExampleIDs removes the "response_examples" edge to InterfaceExample entities by IDs.
func (_u *APIUpdate) RemoveResponseExampleIDs(ids ...int64) *APIUpdate {
	_u.mutation.RemoveResponseExampleIDs(ids...)
	return _u
}

// RemoveResponseExamples removes "response_examples" edges to InterfaceExample entities.
func (_u *APIUpdate) RemoveResponseExamples(v ...*InterfaceExample) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseExampleIDs(ids...)
}

// ClearRequestHeaders clears all "request_headers" edges to the InterfaceRequestHeader entity.
func (_u *APIUpdate) ClearRequestHeaders() *APIUpdate {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// RemoveRequestHeaderIDs removes the "request_headers" edge to InterfaceRequestHeader entities by IDs.
func (_u *APIUpdate) RemoveRequestHeaderIDs(ids ...int64) *APIUpdate {
	_u.mutation.RemoveRequestHeaderIDs(ids...)
	return _u
}

// RemoveRequestHeaders removes "request_headers" edges to InterfaceRequestHeader entities.
func (_u *APIUpdate) RemoveRequestHeaders(v ...*InterfaceRequestHeader) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestHeaderIDs(ids...)
}

// ClearQueryParams clears all "query_params" edges to the InterfaceQueryParam entity.
func (_u *APIUpdate) ClearQueryParams() *APIUpdate {
	_u.mutation.ClearQueryParams()
	return _u
}

// RemoveQueryParamIDs removes the "query_params" edge to InterfaceQueryParam entities by IDs.
func (_u *APIUpdate) RemoveQueryParamIDs(ids ...int64) *APIUpdate {
	_u.mutation.RemoveQueryParamIDs(ids...)
	return _u
}

// RemoveQueryParams removes "query_params" edges to InterfaceQueryParam entities.
func (_u *APIUpdate) RemoveQueryParams(v ...*InterfaceQueryParam) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQueryParamIDs(ids...)
}

// ClearBodyFields clears all "body_fields" edges to the InterfaceBodyField entity.
func (_u *APIUpdate) ClearBodyFields() *APIUpdate {
	_u.mutation.ClearBodyFields()
	return _u
}

// RemoveBodyFieldIDs removes the "body_fields" edge to InterfaceBodyField entities by IDs.
func (_u *APIUpdate) RemoveBodyFieldIDs(ids ...int64) *APIUpdate {
	_u.mutation.RemoveBodyFieldIDs(ids...)
	return _u
}

// RemoveBodyFields removes "body_fields" edges to InterfaceBodyField entities.
func (_u *APIUpdate) RemoveBodyFields(v ...*InterfaceBodyField) *APIUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBodyFieldIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if api.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized api.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := api.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := api.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "API.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := api.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "API.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := api.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "API.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBodyFormat(); ok {
		if err := api.RequestBodyFormatValidator(v); err != nil {
			return &ValidationError{Name: "request_body_format", err: fmt.Errorf(`ent: validator failed for field "API.request_body_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBodyDataType(); ok {
		if err := api.RequestBodyDataTypeValidator(v); err != nil {
			return &ValidationError{Name: "request_body_data_type", err: fmt.Errorf(`ent: validator failed for field "API.request_body_data_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.project"`)
	}
	if _u.mutation.FolderCleared() && len(_u.mutation.FolderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.folder"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.updater"`)
	}
	return nil
}

func (_u *APIUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(api.Table, api.Columns, sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(api.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(api.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(api.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(api.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(api.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.RequestBodyFormat(); ok {
		_spec.SetField(api.FieldRequestBodyFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodyDataType(); ok {
		_spec.SetField(api.FieldRequestBodyDataType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(api.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(api.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(api.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(api.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(api.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(api.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.ProjectTable,
			Columns: []string{api.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.ProjectTable,
			Columns: []string{api.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.FolderTable,
			Columns: []string{api.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.FolderTable,
			Columns: []string{api.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CreatorTable,
			Columns: []string{api.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CreatorTable,
			Columns: []string{api.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.UpdaterTable,
			Columns: []string{api.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.UpdaterTable,
			Columns: []string{api.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseHeadersTable,
			Columns: []string{api.ResponseHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceheader.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseHeadersIDs(); len(nodes) > 0 && !_u.mutation.ResponseHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseHeadersTable,
			Columns: []string{api.ResponseHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseHeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseHeadersTable,
			Columns: []string{api.ResponseHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseResultsTable,
			Columns: []string{api.ResponseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseResultsIDs(); len(nodes) > 0 && !_u.mutation.ResponseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseResultsTable,
			Columns: []string{api.ResponseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseResultsTable,
			Columns: []string{api.ResponseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseExamplesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseExamplesTable,
			Columns: []string{api.ResponseExamplesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceexample.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseExamplesIDs(); len(nodes) > 0 && !_u.mutation.ResponseExamplesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseExamplesTable,
			Columns: []string{api.ResponseExamplesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceexample.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseExamplesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseExamplesTable,
			Columns: []string{api.ResponseExamplesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceexample.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.RequestHeadersTable,
			Columns: []string{api.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacerequestheader.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestHeadersIDs(); len(nodes) > 0 && !_u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.RequestHeadersTable,
			Columns: []string{api.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacerequestheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestHeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.RequestHeadersTable,
			Columns: []string{api.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacerequestheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.QueryParamsTable,
			Columns: []string{api.QueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQueryParamsIDs(); len(nodes) > 0 && !_u.mutation.QueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.QueryParamsTable,
			Columns: []string{api.QueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QueryParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.QueryParamsTable,
			Columns: []string{api.QueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BodyFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.BodyFieldsTable,
			Columns: []string{api.BodyFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacebodyfield.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBodyFieldsIDs(); len(nodes) > 0 && !_u.mutation.BodyFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.BodyFieldsTable,
			Columns: []string{api.BodyFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacebodyfield.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BodyFieldsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.BodyFieldsTable,
			Columns: []string{api.BodyFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacebodyfield.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{api.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIUpdateOne is the builder for updating a single API entity.
type APIUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIMutation
}

// SetProjectID sets the "project_id" field.
func (_u *APIUpdateOne) SetProjectID(v int64) *APIUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableProjectID(v *int64) *APIUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *APIUpdateOne) SetFolderID(v int64) *APIUpdateOne {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableFolderID(v *int64) *APIUpdateOne {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *APIUpdateOne) SetName(v string) *APIUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableName(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *APIUpdateOne) SetMethod(v string) *APIUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableMethod(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *APIUpdateOne) SetURL(v string) *APIUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableURL(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *APIUpdateOne) SetStatus(v uint8) *APIUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableStatus(v *uint8) *APIUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *APIUpdateOne) AddStatus(v int8) *APIUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetRequestBodyFormat sets the "request_body_format" field.
func (_u *APIUpdateOne) SetRequestBodyFormat(v string) *APIUpdateOne {
	_u.mutation.SetRequestBodyFormat(v)
	return _u
}

// SetNillableRequestBodyFormat sets the "request_body_format" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableRequestBodyFormat(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetRequestBodyFormat(*v)
	}
	return _u
}

// SetRequestBodyDataType sets the "request_body_data_type" field.
func (_u *APIUpdateOne) SetRequestBodyDataType(v string) *APIUpdateOne {
	_u.mutation.SetRequestBodyDataType(v)
	return _u
}

// SetNillableRequestBodyDataType sets the "request_body_data_type" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableRequestBodyDataType(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetRequestBodyDataType(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *APIUpdateOne) SetSortOrder(v int) *APIUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableSortOrder(v *int) *APIUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *APIUpdateOne) AddSortOrder(v int) *APIUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *APIUpdateOne) SetCreatedBy(v int64) *APIUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableCreatedBy(v *int64) *APIUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *APIUpdateOne) SetUpdatedBy(v int64) *APIUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableUpdatedBy(v *int64) *APIUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *APIUpdateOne) SetCreatedAt(v utils.DateTime) *APIUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableCreatedAt(v *utils.DateTime) *APIUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIUpdateOne) SetUpdatedAt(v utils.DateTime) *APIUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *APIUpdateOne) SetDeletedAt(v utils.DateTime) *APIUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableDeletedAt(v *utils.DateTime) *APIUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *APIUpdateOne) ClearDeletedAt() *APIUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *APIUpdateOne) SetProject(v *Project) *APIUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetFolder sets the "folder" edge to the Folder entity.
func (_u *APIUpdateOne) SetFolder(v *Folder) *APIUpdateOne {
	return _u.SetFolderID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *APIUpdateOne) SetCreatorID(id int64) *APIUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *APIUpdateOne) SetCreator(v *User) *APIUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *APIUpdateOne) SetUpdaterID(id int64) *APIUpdateOne {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *APIUpdateOne) SetUpdater(v *User) *APIUpdateOne {
	return _u.SetUpdaterID(v.ID)
}

// AddResponseHeaderIDs adds the "response_headers" edge to the InterfaceHeader entity by IDs.
func (_u *APIUpdateOne) AddResponseHeaderIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.AddResponseHeaderIDs(ids...)
	return _u
}

// AddResponseHeaders adds the "response_headers" edges to the InterfaceHeader entity.
func (_u *APIUpdateOne) AddResponseHeaders(v ...*InterfaceHeader) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseHeaderIDs(ids...)
}

// AddResponseResultIDs adds the "response_results" edge to the InterfaceResult entity by IDs.
func (_u *APIUpdateOne) AddResponseResultIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.AddResponseResultIDs(ids...)
	return _u
}

// AddResponseResults adds the "response_results" edges to the InterfaceResult entity.
func (_u *APIUpdateOne) AddResponseResults(v ...*InterfaceResult) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseResultIDs(ids...)
}

// AddResponseExampleIDs adds the "response_examples" edge to the InterfaceExample entity by IDs.
func (_u *APIUpdateOne) AddResponseExampleIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.AddResponseExampleIDs(ids...)
	return _u
}

// AddResponseExamples adds the "response_examples" edges to the InterfaceExample entity.
func (_u *APIUpdateOne) AddResponseExamples(v ...*InterfaceExample) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseExampleIDs(ids...)
}

// AddRequestHeaderIDs adds the "request_headers" edge to the InterfaceRequestHeader entity by IDs.
func (_u *APIUpdateOne) AddRequestHeaderIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.AddRequestHeaderIDs(ids...)
	return _u
}

// AddRequestHeaders adds the "request_headers" edges to the InterfaceRequestHeader entity.
func (_u *APIUpdateOne) AddRequestHeaders(v ...*InterfaceRequestHeader) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestHeaderIDs(ids...)
}

// AddQueryParamIDs adds the "query_params" edge to the InterfaceQueryParam entity by IDs.
func (_u *APIUpdateOne) AddQueryParamIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.AddQueryParamIDs(ids...)
	return _u
}

// AddQueryParams adds the "query_params" edges to the InterfaceQueryParam entity.
func (_u *APIUpdateOne) AddQueryParams(v ...*InterfaceQueryParam) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQueryParamIDs(ids...)
}

// AddBodyFieldIDs adds the "body_fields" edge to the InterfaceBodyField entity by IDs.
func (_u *APIUpdateOne) AddBodyFieldIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.AddBodyFieldIDs(ids...)
	return _u
}

// AddBodyFields adds the "body_fields" edges to the InterfaceBodyField entity.
func (_u *APIUpdateOne) AddBodyFields(v ...*InterfaceBodyField) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBodyFieldIDs(ids...)
}

// Mutation returns the APIMutation object of the builder.
func (_u *APIUpdateOne) Mutation() *APIMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *APIUpdateOne) ClearProject() *APIUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearFolder clears the "folder" edge to the Folder entity.
func (_u *APIUpdateOne) ClearFolder() *APIUpdateOne {
	_u.mutation.ClearFolder()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *APIUpdateOne) ClearCreator() *APIUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *APIUpdateOne) ClearUpdater() *APIUpdateOne {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearResponseHeaders clears all "response_headers" edges to the InterfaceHeader entity.
func (_u *APIUpdateOne) ClearResponseHeaders() *APIUpdateOne {
	_u.mutation.ClearResponseHeaders()
	return _u
}

// RemoveResponseHeaderIDs removes the "response_headers" edge to InterfaceHeader entities by IDs.
func (_u *APIUpdateOne) RemoveResponseHeaderIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.RemoveResponseHeaderIDs(ids...)
	return _u
}

// RemoveResponseHeaders removes "response_headers" edges to InterfaceHeader entities.
func (_u *APIUpdateOne) RemoveResponseHeaders(v ...*InterfaceHeader) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseHeaderIDs(ids...)
}

// ClearResponseResults clears all "response_results" edges to the InterfaceResult entity.
func (_u *APIUpdateOne) ClearResponseResults() *APIUpdateOne {
	_u.mutation.ClearResponseResults()
	return _u
}

// RemoveResponseResultIDs removes the "response_results" edge to InterfaceResult entities by IDs.
func (_u *APIUpdateOne) RemoveResponseResultIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.RemoveResponseResultIDs(ids...)
	return _u
}

// RemoveResponseResults removes "response_results" edges to InterfaceResult entities.
func (_u *APIUpdateOne) RemoveResponseResults(v ...*InterfaceResult) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseResultIDs(ids...)
}

// ClearResponseExamples clears all "response_examples" edges to the InterfaceExample entity.
func (_u *APIUpdateOne) ClearResponseExamples() *APIUpdateOne {
	_u.mutation.ClearResponseExamples()
	return _u
}

// RemoveResponseExampleIDs removes the "response_examples" edge to InterfaceExample entities by IDs.
func (_u *APIUpdateOne) RemoveResponseExampleIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.RemoveResponseExampleIDs(ids...)
	return _u
}

// RemoveResponseExamples removes "response_examples" edges to InterfaceExample entities.
func (_u *APIUpdateOne) RemoveResponseExamples(v ...*InterfaceExample) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseExampleIDs(ids...)
}

// ClearRequestHeaders clears all "request_headers" edges to the InterfaceRequestHeader entity.
func (_u *APIUpdateOne) ClearRequestHeaders() *APIUpdateOne {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// RemoveRequestHeaderIDs removes the "request_headers" edge to InterfaceRequestHeader entities by IDs.
func (_u *APIUpdateOne) RemoveRequestHeaderIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.RemoveRequestHeaderIDs(ids...)
	return _u
}

// RemoveRequestHeaders removes "request_headers" edges to InterfaceRequestHeader entities.
func (_u *APIUpdateOne) RemoveRequestHeaders(v ...*InterfaceRequestHeader) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestHeaderIDs(ids...)
}

// ClearQueryParams clears all "query_params" edges to the InterfaceQueryParam entity.
func (_u *APIUpdateOne) ClearQueryParams() *APIUpdateOne {
	_u.mutation.ClearQueryParams()
	return _u
}

// RemoveQueryParamIDs removes the "query_params" edge to InterfaceQueryParam entities by IDs.
func (_u *APIUpdateOne) RemoveQueryParamIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.RemoveQueryParamIDs(ids...)
	return _u
}

// RemoveQueryParams removes "query_params" edges to InterfaceQueryParam entities.
func (_u *APIUpdateOne) RemoveQueryParams(v ...*InterfaceQueryParam) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQueryParamIDs(ids...)
}

// ClearBodyFields clears all "body_fields" edges to the InterfaceBodyField entity.
func (_u *APIUpdateOne) ClearBodyFields() *APIUpdateOne {
	_u.mutation.ClearBodyFields()
	return _u
}

// RemoveBodyFieldIDs removes the "body_fields" edge to InterfaceBodyField entities by IDs.
func (_u *APIUpdateOne) RemoveBodyFieldIDs(ids ...int64) *APIUpdateOne {
	_u.mutation.RemoveBodyFieldIDs(ids...)
	return _u
}

// RemoveBodyFields removes "body_fields" edges to InterfaceBodyField entities.
func (_u *APIUpdateOne) RemoveBodyFields(v ...*InterfaceBodyField) *APIUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBodyFieldIDs(ids...)
}

// Where appends a list predicates to the APIUpdate builder.
func (_u *APIUpdateOne) Where(ps ...predicate.API) *APIUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIUpdateOne) Select(field string, fields ...string) *APIUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated API entity.
func (_u *APIUpdateOne) Save(ctx context.Context) (*API, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIUpdateOne) SaveX(ctx context.Context) *API {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if api.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized api.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := api.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := api.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "API.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := api.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "API.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := api.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "API.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBodyFormat(); ok {
		if err := api.RequestBodyFormatValidator(v); err != nil {
			return &ValidationError{Name: "request_body_format", err: fmt.Errorf(`ent: validator failed for field "API.request_body_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestBodyDataType(); ok {
		if err := api.RequestBodyDataTypeValidator(v); err != nil {
			return &ValidationError{Name: "request_body_data_type", err: fmt.Errorf(`ent: validator failed for field "API.request_body_data_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.project"`)
	}
	if _u.mutation.FolderCleared() && len(_u.mutation.FolderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.folder"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "API.updater"`)
	}
	return nil
}

func (_u *APIUpdateOne) sqlSave(ctx context.Context) (_node *API, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(api.Table, api.Columns, sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "API.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, api.FieldID)
		for _, f := range fields {
			if !api.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != api.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(api.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(api.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(api.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(api.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(api.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.RequestBodyFormat(); ok {
		_spec.SetField(api.FieldRequestBodyFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestBodyDataType(); ok {
		_spec.SetField(api.FieldRequestBodyDataType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(api.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(api.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(api.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(api.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(api.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(api.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.ProjectTable,
			Columns: []string{api.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.ProjectTable,
			Columns: []string{api.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FolderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.FolderTable,
			Columns: []string{api.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.FolderTable,
			Columns: []string{api.FolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CreatorTable,
			Columns: []string{api.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CreatorTable,
			Columns: []string{api.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.UpdaterTable,
			Columns: []string{api.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.UpdaterTable,
			Columns: []string{api.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseHeadersTable,
			Columns: []string{api.ResponseHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceheader.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseHeadersIDs(); len(nodes) > 0 && !_u.mutation.ResponseHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseHeadersTable,
			Columns: []string{api.ResponseHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseHeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseHeadersTable,
			Columns: []string{api.ResponseHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseResultsTable,
			Columns: []string{api.ResponseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseResultsIDs(); len(nodes) > 0 && !_u.mutation.ResponseResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseResultsTable,
			Columns: []string{api.ResponseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseResultsTable,
			Columns: []string{api.ResponseResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseExamplesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseExamplesTable,
			Columns: []string{api.ResponseExamplesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceexample.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseExamplesIDs(); len(nodes) > 0 && !_u.mutation.ResponseExamplesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseExamplesTable,
			Columns: []string{api.ResponseExamplesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceexample.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseExamplesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponseExamplesTable,
			Columns: []string{api.ResponseExamplesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfaceexample.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.RequestHeadersTable,
			Columns: []string{api.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacerequestheader.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestHeadersIDs(); len(nodes) > 0 && !_u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.RequestHeadersTable,
			Columns: []string{api.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacerequestheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestHeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.RequestHeadersTable,
			Columns: []string{api.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacerequestheader.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.QueryParamsTable,
			Columns: []string{api.QueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQueryParamsIDs(); len(nodes) > 0 && !_u.mutation.QueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.QueryParamsTable,
			Columns: []string{api.QueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QueryParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.QueryParamsTable,
			Columns: []string{api.QueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BodyFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.BodyFieldsTable,
			Columns: []string{api.BodyFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacebodyfield.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBodyFieldsIDs(); len(nodes) > 0 && !_u.mutation.BodyFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.BodyFieldsTable,
			Columns: []string{api.BodyFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacebodyfield.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BodyFieldsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.BodyFieldsTable,
			Columns: []string{api.BodyFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacebodyfield.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &API{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{api.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
