// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nest-api/internal/ent/environment"
	"nest-api/internal/ent/environmentvariable"
	"nest-api/internal/ent/project"
	"nest-api/internal/ent/user"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnvironmentCreate is the builder for creating a Environment entity.
type EnvironmentCreate struct {
	config
	mutation *EnvironmentMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *EnvironmentCreate) SetProjectID(v int64) *EnvironmentCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableProjectID(v *int64) *EnvironmentCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *EnvironmentCreate) SetName(v string) *EnvironmentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableName(v *string) *EnvironmentCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *EnvironmentCreate) SetRemark(v string) *EnvironmentCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableRemark(v *string) *EnvironmentCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *EnvironmentCreate) SetIsDefault(v bool) *EnvironmentCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableIsDefault(v *bool) *EnvironmentCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EnvironmentCreate) SetCreatedBy(v int64) *EnvironmentCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableCreatedBy(v *int64) *EnvironmentCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnvironmentCreate) SetCreatedAt(v utils.DateTime) *EnvironmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableCreatedAt(v *utils.DateTime) *EnvironmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnvironmentCreate) SetUpdatedAt(v utils.DateTime) *EnvironmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableUpdatedAt(v *utils.DateTime) *EnvironmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EnvironmentCreate) SetDeletedAt(v utils.DateTime) *EnvironmentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EnvironmentCreate) SetNillableDeletedAt(v *utils.DateTime) *EnvironmentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EnvironmentCreate) SetID(v int64) *EnvironmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *EnvironmentCreate) SetProject(v *Project) *EnvironmentCreate {
	return _c.SetProjectID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *EnvironmentCreate) SetCreatorID(id int64) *EnvironmentCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *EnvironmentCreate) SetCreator(v *User) *EnvironmentCreate {
	return _c.SetCreatorID(v.ID)
}

// AddVariableIDs adds the "variables" edge to the EnvironmentVariable entity by IDs.
func (_c *EnvironmentCreate) AddVariableIDs(ids ...int64) *EnvironmentCreate {
	_c.mutation.AddVariableIDs(ids...)
	return _c
}

// AddVariables adds the "variables" edges to the EnvironmentVariable entity.
func (_c *EnvironmentCreate) AddVariables(v ...*EnvironmentVariable) *EnvironmentCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVariableIDs(ids...)
}

// Mutation returns the EnvironmentMutation object of the builder.
func (_c *EnvironmentCreate) Mutation() *EnvironmentMutation {
	return _c.mutation
}

// Save creates the Environment in the database.
func (_c *EnvironmentCreate) Save(ctx context.Context) (*Environment, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnvironmentCreate) SaveX(ctx context.Context) *Environment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvironmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvironmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnvironmentCreate) defaults() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		v := environment.DefaultProjectID
		_c.mutation.SetProjectID(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := environment.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := environment.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := environment.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := environment.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if environment.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized environment.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := environment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if environment.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized environment.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := environment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnvironmentCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Environment.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Environment.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := environment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Environment.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "Environment.remark"`)}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := environment.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "Environment.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "Environment.is_default"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Environment.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Environment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Environment.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := environment.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Environment.id": %w`, err)}
		}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Environment.project"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Environment.creator"`)}
	}
	return nil
}

func (_c *EnvironmentCreate) sqlSave(ctx context.Context) (*Environment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnvironmentCreate) createSpec() (*Environment, *sqlgraph.CreateSpec) {
	var (
		_node = &Environment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(environment.Table, sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(environment.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(environment.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(environment.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(environment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(environment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(environment.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.ProjectTable,
			Columns: []string{environment.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environment.CreatorTable,
			Columns: []string{environment.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VariablesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   environment.VariablesTable,
			Columns: []string{environment.VariablesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environmentvariable.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnvironmentCreateBulk is the builder for creating many Environment entities in bulk.
type EnvironmentCreateBulk struct {
	config
	err      error
	builders []*EnvironmentCreate
}

// Save creates the Environment entities in the database.
func (_c *EnvironmentCreateBulk) Save(ctx context.Context) ([]*Environment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Environment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnvironmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnvironmentCreateBulk) SaveX(ctx context.Context) []*Environment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvironmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvironmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
