// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nest-api/internal/ent/environment"
	"nest-api/internal/ent/environmentvariable"
	"nest-api/internal/ent/user"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EnvironmentVariableCreate is the builder for creating a EnvironmentVariable entity.
type EnvironmentVariableCreate struct {
	config
	mutation *EnvironmentVariableMutation
	hooks    []Hook
}

// SetEnvironmentID sets the "environment_id" field.
func (_c *EnvironmentVariableCreate) SetEnvironmentID(v int64) *EnvironmentVariableCreate {
	_c.mutation.SetEnvironmentID(v)
	return _c
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableEnvironmentID(v *int64) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetEnvironmentID(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *EnvironmentVariableCreate) SetKey(v string) *EnvironmentVariableCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableKey(v *string) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetKey(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *EnvironmentVariableCreate) SetValue(v string) *EnvironmentVariableCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableValue(v *string) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *EnvironmentVariableCreate) SetDescription(v string) *EnvironmentVariableCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableDescription(v *string) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *EnvironmentVariableCreate) SetCreatedBy(v int64) *EnvironmentVariableCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableCreatedBy(v *int64) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnvironmentVariableCreate) SetCreatedAt(v utils.DateTime) *EnvironmentVariableCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableCreatedAt(v *utils.DateTime) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnvironmentVariableCreate) SetUpdatedAt(v utils.DateTime) *EnvironmentVariableCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableUpdatedAt(v *utils.DateTime) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EnvironmentVariableCreate) SetDeletedAt(v utils.DateTime) *EnvironmentVariableCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EnvironmentVariableCreate) SetNillableDeletedAt(v *utils.DateTime) *EnvironmentVariableCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EnvironmentVariableCreate) SetID(v int64) *EnvironmentVariableCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetEnvironment sets the "environment" edge to the Environment entity.
func (_c *EnvironmentVariableCreate) SetEnvironment(v *Environment) *EnvironmentVariableCreate {
	return _c.SetEnvironmentID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *EnvironmentVariableCreate) SetCreatorID(id int64) *EnvironmentVariableCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *EnvironmentVariableCreate) SetCreator(v *User) *EnvironmentVariableCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the EnvironmentVariableMutation object of the builder.
func (_c *EnvironmentVariableCreate) Mutation() *EnvironmentVariableMutation {
	return _c.mutation
}

// Save creates the EnvironmentVariable in the database.
func (_c *EnvironmentVariableCreate) Save(ctx context.Context) (*EnvironmentVariable, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnvironmentVariableCreate) SaveX(ctx context.Context) *EnvironmentVariable {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvironmentVariableCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvironmentVariableCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnvironmentVariableCreate) defaults() error {
	if _, ok := _c.mutation.EnvironmentID(); !ok {
		v := environmentvariable.DefaultEnvironmentID
		_c.mutation.SetEnvironmentID(v)
	}
	if _, ok := _c.mutation.Key(); !ok {
		v := environmentvariable.DefaultKey
		_c.mutation.SetKey(v)
	}
	if _, ok := _c.mutation.Value(); !ok {
		v := environmentvariable.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := environmentvariable.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := environmentvariable.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if environmentvariable.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized environmentvariable.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := environmentvariable.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if environmentvariable.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized environmentvariable.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := environmentvariable.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnvironmentVariableCreate) check() error {
	if _, ok := _c.mutation.EnvironmentID(); !ok {
		return &ValidationError{Name: "environment_id", err: errors.New(`ent: missing required field "EnvironmentVariable.environment_id"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "EnvironmentVariable.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := environmentvariable.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "EnvironmentVariable.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "EnvironmentVariable.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := environmentvariable.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "EnvironmentVariable.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "EnvironmentVariable.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := environmentvariable.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "EnvironmentVariable.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "EnvironmentVariable.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnvironmentVariable.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnvironmentVariable.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := environmentvariable.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "EnvironmentVariable.id": %w`, err)}
		}
	}
	if len(_c.mutation.EnvironmentIDs()) == 0 {
		return &ValidationError{Name: "environment", err: errors.New(`ent: missing required edge "EnvironmentVariable.environment"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "EnvironmentVariable.creator"`)}
	}
	return nil
}

func (_c *EnvironmentVariableCreate) sqlSave(ctx context.Context) (*EnvironmentVariable, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnvironmentVariableCreate) createSpec() (*EnvironmentVariable, *sqlgraph.CreateSpec) {
	var (
		_node = &EnvironmentVariable{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(environmentvariable.Table, sqlgraph.NewFieldSpec(environmentvariable.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(environmentvariable.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(environmentvariable.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(environmentvariable.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(environmentvariable.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(environmentvariable.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(environmentvariable.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.EnvironmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environmentvariable.EnvironmentTable,
			Columns: []string{environmentvariable.EnvironmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(environment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnvironmentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   environmentvariable.CreatorTable,
			Columns: []string{environmentvariable.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnvironmentVariableCreateBulk is the builder for creating many EnvironmentVariable entities in bulk.
type EnvironmentVariableCreateBulk struct {
	config
	err      error
	builders []*EnvironmentVariableCreate
}

// Save creates the EnvironmentVariable entities in the database.
func (_c *EnvironmentVariableCreateBulk) Save(ctx context.Context) ([]*EnvironmentVariable, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnvironmentVariable, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnvironmentVariableMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnvironmentVariableCreateBulk) SaveX(ctx context.Context) []*EnvironmentVariable {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnvironmentVariableCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnvironmentVariableCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
