// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nest-api/internal/ent/interfacefield"
	"nest-api/internal/ent/interfaceresult"
	"nest-api/internal/utils"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InterfaceField is the model entity for the InterfaceField schema.
type InterfaceField struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID int64 `json:"id,omitempty"`
	// 返回结果 ID
	ResultID int64 `json:"result_id,omitempty"`
	// 父字段 ID
	ParentID int64 `json:"parent_id,omitempty"`
	// 参数名
	Name string `json:"name,omitempty"`
	// 类型
	Type string `json:"type,omitempty"`
	// 是否必填
	Required bool `json:"required,omitempty"`
	// 说明
	Description string `json:"description,omitempty"`
	// Mock
	Mock string `json:"mock,omitempty"`
	// 参数示例
	Example string `json:"example,omitempty"`
	// 排序
	SortOrder int `json:"sort_order,omitempty"`
	// 创建时间
	CreatedAt utils.DateTime `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt utils.DateTime `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *utils.DateTime `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InterfaceFieldQuery when eager-loading is set.
	Edges        InterfaceFieldEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InterfaceFieldEdges holds the relations/edges for other nodes in the graph.
type InterfaceFieldEdges struct {
	// Result holds the value of the result edge.
	Result *InterfaceResult `json:"result,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ResultOrErr returns the Result value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InterfaceFieldEdges) ResultOrErr() (*InterfaceResult, error) {
	if e.Result != nil {
		return e.Result, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: interfaceresult.Label}
	}
	return nil, &NotLoadedError{edge: "result"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InterfaceField) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case interfacefield.FieldDeletedAt:
			values[i] = &sql.NullScanner{S: new(utils.DateTime)}
		case interfacefield.FieldRequired:
			values[i] = new(sql.NullBool)
		case interfacefield.FieldID, interfacefield.FieldResultID, interfacefield.FieldParentID, interfacefield.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case interfacefield.FieldName, interfacefield.FieldType, interfacefield.FieldDescription, interfacefield.FieldMock, interfacefield.FieldExample:
			values[i] = new(sql.NullString)
		case interfacefield.FieldCreatedAt, interfacefield.FieldUpdatedAt:
			values[i] = new(utils.DateTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InterfaceField fields.
func (_m *InterfaceField) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case interfacefield.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case interfacefield.FieldResultID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result_id", values[i])
			} else if value.Valid {
				_m.ResultID = value.Int64
			}
		case interfacefield.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = value.Int64
			}
		case interfacefield.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case interfacefield.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case interfacefield.FieldRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field required", values[i])
			} else if value.Valid {
				_m.Required = value.Bool
			}
		case interfacefield.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case interfacefield.FieldMock:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mock", values[i])
			} else if value.Valid {
				_m.Mock = value.String
			}
		case interfacefield.FieldExample:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field example", values[i])
			} else if value.Valid {
				_m.Example = value.String
			}
		case interfacefield.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case interfacefield.FieldCreatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil {
				_m.CreatedAt = *value
			}
		case interfacefield.FieldUpdatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value != nil {
				_m.UpdatedAt = *value
			}
		case interfacefield.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(utils.DateTime)
				*_m.DeletedAt = *value.S.(*utils.DateTime)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InterfaceField.
// This includes values selected through modifiers, order, etc.
func (_m *InterfaceField) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryResult queries the "result" edge of the InterfaceField entity.
func (_m *InterfaceField) QueryResult() *InterfaceResultQuery {
	return NewInterfaceFieldClient(_m.config).QueryResult(_m)
}

// Update returns a builder for updating this InterfaceField.
// Note that you need to call InterfaceField.Unwrap() before calling this method if this InterfaceField
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InterfaceField) Update() *InterfaceFieldUpdateOne {
	return NewInterfaceFieldClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InterfaceField entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InterfaceField) Unwrap() *InterfaceField {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InterfaceField is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InterfaceField) String() string {
	var builder strings.Builder
	builder.WriteString("InterfaceField(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("result_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultID))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("required=")
	builder.WriteString(fmt.Sprintf("%v", _m.Required))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("mock=")
	builder.WriteString(_m.Mock)
	builder.WriteString(", ")
	builder.WriteString("example=")
	builder.WriteString(_m.Example)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InterfaceFields is a parsable slice of InterfaceField.
type InterfaceFields []*InterfaceField
