// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nest-api/internal/ent/api"
	"nest-api/internal/ent/interfacefield"
	"nest-api/internal/ent/interfaceresult"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceResultCreate is the builder for creating a InterfaceResult entity.
type InterfaceResultCreate struct {
	config
	mutation *InterfaceResultMutation
	hooks    []Hook
}

// SetInterfaceID sets the "interface_id" field.
func (_c *InterfaceResultCreate) SetInterfaceID(v int64) *InterfaceResultCreate {
	_c.mutation.SetInterfaceID(v)
	return _c
}

// SetNillableInterfaceID sets the "interface_id" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableInterfaceID(v *int64) *InterfaceResultCreate {
	if v != nil {
		_c.SetInterfaceID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *InterfaceResultCreate) SetName(v string) *InterfaceResultCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableName(v *string) *InterfaceResultCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *InterfaceResultCreate) SetStatusCode(v int) *InterfaceResultCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableStatusCode(v *int) *InterfaceResultCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetFormat sets the "format" field.
func (_c *InterfaceResultCreate) SetFormat(v string) *InterfaceResultCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableFormat(v *string) *InterfaceResultCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetDataType sets the "data_type" field.
func (_c *InterfaceResultCreate) SetDataType(v string) *InterfaceResultCreate {
	_c.mutation.SetDataType(v)
	return _c
}

// SetNillableDataType sets the "data_type" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableDataType(v *string) *InterfaceResultCreate {
	if v != nil {
		_c.SetDataType(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *InterfaceResultCreate) SetSortOrder(v int) *InterfaceResultCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableSortOrder(v *int) *InterfaceResultCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InterfaceResultCreate) SetCreatedAt(v utils.DateTime) *InterfaceResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableCreatedAt(v *utils.DateTime) *InterfaceResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InterfaceResultCreate) SetUpdatedAt(v utils.DateTime) *InterfaceResultCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableUpdatedAt(v *utils.DateTime) *InterfaceResultCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *InterfaceResultCreate) SetDeletedAt(v utils.DateTime) *InterfaceResultCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *InterfaceResultCreate) SetNillableDeletedAt(v *utils.DateTime) *InterfaceResultCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InterfaceResultCreate) SetID(v int64) *InterfaceResultCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetInterface sets the "interface" edge to the API entity.
func (_c *InterfaceResultCreate) SetInterface(v *API) *InterfaceResultCreate {
	return _c.SetInterfaceID(v.ID)
}

// AddFieldIDs adds the "fields" edge to the InterfaceField entity by IDs.
func (_c *InterfaceResultCreate) AddFieldIDs(ids ...int64) *InterfaceResultCreate {
	_c.mutation.AddFieldIDs(ids...)
	return _c
}

// AddFields adds the "fields" edges to the InterfaceField entity.
func (_c *InterfaceResultCreate) AddFields(v ...*InterfaceField) *InterfaceResultCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFieldIDs(ids...)
}

// Mutation returns the InterfaceResultMutation object of the builder.
func (_c *InterfaceResultCreate) Mutation() *InterfaceResultMutation {
	return _c.mutation
}

// Save creates the InterfaceResult in the database.
func (_c *InterfaceResultCreate) Save(ctx context.Context) (*InterfaceResult, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InterfaceResultCreate) SaveX(ctx context.Context) *InterfaceResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InterfaceResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InterfaceResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InterfaceResultCreate) defaults() error {
	if _, ok := _c.mutation.InterfaceID(); !ok {
		v := interfaceresult.DefaultInterfaceID
		_c.mutation.SetInterfaceID(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := interfaceresult.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := interfaceresult.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.Format(); !ok {
		v := interfaceresult.DefaultFormat
		_c.mutation.SetFormat(v)
	}
	if _, ok := _c.mutation.DataType(); !ok {
		v := interfaceresult.DefaultDataType
		_c.mutation.SetDataType(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := interfaceresult.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if interfaceresult.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized interfaceresult.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := interfaceresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if interfaceresult.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized interfaceresult.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := interfaceresult.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *InterfaceResultCreate) check() error {
	if _, ok := _c.mutation.InterfaceID(); !ok {
		return &ValidationError{Name: "interface_id", err: errors.New(`ent: missing required field "InterfaceResult.interface_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "InterfaceResult.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := interfaceresult.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InterfaceResult.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "InterfaceResult.status_code"`)}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "InterfaceResult.format"`)}
	}
	if v, ok := _c.mutation.Format(); ok {
		if err := interfaceresult.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "InterfaceResult.format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataType(); !ok {
		return &ValidationError{Name: "data_type", err: errors.New(`ent: missing required field "InterfaceResult.data_type"`)}
	}
	if v, ok := _c.mutation.DataType(); ok {
		if err := interfaceresult.DataTypeValidator(v); err != nil {
			return &ValidationError{Name: "data_type", err: fmt.Errorf(`ent: validator failed for field "InterfaceResult.data_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "InterfaceResult.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InterfaceResult.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InterfaceResult.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := interfaceresult.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "InterfaceResult.id": %w`, err)}
		}
	}
	if len(_c.mutation.InterfaceIDs()) == 0 {
		return &ValidationError{Name: "interface", err: errors.New(`ent: missing required edge "InterfaceResult.interface"`)}
	}
	return nil
}

func (_c *InterfaceResultCreate) sqlSave(ctx context.Context) (*InterfaceResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InterfaceResultCreate) createSpec() (*InterfaceResult, *sqlgraph.CreateSpec) {
	var (
		_node = &InterfaceResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(interfaceresult.Table, sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(interfaceresult.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(interfaceresult.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(interfaceresult.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.DataType(); ok {
		_spec.SetField(interfaceresult.FieldDataType, field.TypeString, value)
		_node.DataType = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(interfaceresult.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(interfaceresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(interfaceresult.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(interfaceresult.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.InterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   interfaceresult.InterfaceTable,
			Columns: []string{interfaceresult.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InterfaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FieldsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   interfaceresult.FieldsTable,
			Columns: []string{interfaceresult.FieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(interfacefield.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InterfaceResultCreateBulk is the builder for creating many InterfaceResult entities in bulk.
type InterfaceResultCreateBulk struct {
	config
	err      error
	builders []*InterfaceResultCreate
}

// Save creates the InterfaceResult entities in the database.
func (_c *InterfaceResultCreateBulk) Save(ctx context.Context) ([]*InterfaceResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InterfaceResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InterfaceResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InterfaceResultCreateBulk) SaveX(ctx context.Context) []*InterfaceResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InterfaceResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InterfaceResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
