// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nest-api/internal/ent/interfaceexample"
	"nest-api/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceExampleDelete is the builder for deleting a InterfaceExample entity.
type InterfaceExampleDelete struct {
	config
	hooks    []Hook
	mutation *InterfaceExampleMutation
}

// Where appends a list predicates to the InterfaceExampleDelete builder.
func (_d *InterfaceExampleDelete) Where(ps ...predicate.InterfaceExample) *InterfaceExampleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InterfaceExampleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InterfaceExampleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InterfaceExampleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(interfaceexample.Table, sqlgraph.NewFieldSpec(interfaceexample.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InterfaceExampleDeleteOne is the builder for deleting a single InterfaceExample entity.
type InterfaceExampleDeleteOne struct {
	_d *InterfaceExampleDelete
}

// Where appends a list predicates to the InterfaceExampleDelete builder.
func (_d *InterfaceExampleDeleteOne) Where(ps ...predicate.InterfaceExample) *InterfaceExampleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InterfaceExampleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{interfaceexample.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InterfaceExampleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
