// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nest-api/internal/ent/interfacequeryparam"
	"nest-api/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceQueryParamDelete is the builder for deleting a InterfaceQueryParam entity.
type InterfaceQueryParamDelete struct {
	config
	hooks    []Hook
	mutation *InterfaceQueryParamMutation
}

// Where appends a list predicates to the InterfaceQueryParamDelete builder.
func (_d *InterfaceQueryParamDelete) Where(ps ...predicate.InterfaceQueryParam) *InterfaceQueryParamDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InterfaceQueryParamDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InterfaceQueryParamDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InterfaceQueryParamDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(interfacequeryparam.Table, sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InterfaceQueryParamDeleteOne is the builder for deleting a single InterfaceQueryParam entity.
type InterfaceQueryParamDeleteOne struct {
	_d *InterfaceQueryParamDelete
}

// Where appends a list predicates to the InterfaceQueryParamDelete builder.
func (_d *InterfaceQueryParamDeleteOne) Where(ps ...predicate.InterfaceQueryParam) *InterfaceQueryParamDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InterfaceQueryParamDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{interfacequeryparam.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InterfaceQueryParamDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
