// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"nest-api/internal/ent/api"
	"nest-api/internal/ent/interfacefield"
	"nest-api/internal/ent/interfaceresult"
	"nest-api/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceResultQuery is the builder for querying InterfaceResult entities.
type InterfaceResultQuery struct {
	config
	ctx           *QueryContext
	order         []interfaceresult.OrderOption
	inters        []Interceptor
	predicates    []predicate.InterfaceResult
	withInterface *APIQuery
	withFields    *InterfaceFieldQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InterfaceResultQuery builder.
func (_q *InterfaceResultQuery) Where(ps ...predicate.InterfaceResult) *InterfaceResultQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *InterfaceResultQuery) Limit(limit int) *InterfaceResultQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *InterfaceResultQuery) Offset(offset int) *InterfaceResultQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *InterfaceResultQuery) Unique(unique bool) *InterfaceResultQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *InterfaceResultQuery) Order(o ...interfaceresult.OrderOption) *InterfaceResultQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryInterface chains the current query on the "interface" edge.
func (_q *InterfaceResultQuery) QueryInterface() *APIQuery {
	query := (&APIClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(interfaceresult.Table, interfaceresult.FieldID, selector),
			sqlgraph.To(api.Table, api.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, interfaceresult.InterfaceTable, interfaceresult.InterfaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFields chains the current query on the "fields" edge.
func (_q *InterfaceResultQuery) QueryFields() *InterfaceFieldQuery {
	query := (&InterfaceFieldClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(interfaceresult.Table, interfaceresult.FieldID, selector),
			sqlgraph.To(interfacefield.Table, interfacefield.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, interfaceresult.FieldsTable, interfaceresult.FieldsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InterfaceResult entity from the query.
// Returns a *NotFoundError when no InterfaceResult was found.
func (_q *InterfaceResultQuery) First(ctx context.Context) (*InterfaceResult, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{interfaceresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *InterfaceResultQuery) FirstX(ctx context.Context) *InterfaceResult {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InterfaceResult ID from the query.
// Returns a *NotFoundError when no InterfaceResult ID was found.
func (_q *InterfaceResultQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{interfaceresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *InterfaceResultQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InterfaceResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InterfaceResult entity is found.
// Returns a *NotFoundError when no InterfaceResult entities are found.
func (_q *InterfaceResultQuery) Only(ctx context.Context) (*InterfaceResult, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{interfaceresult.Label}
	default:
		return nil, &NotSingularError{interfaceresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *InterfaceResultQuery) OnlyX(ctx context.Context) *InterfaceResult {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InterfaceResult ID in the query.
// Returns a *NotSingularError when more than one InterfaceResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *InterfaceResultQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{interfaceresult.Label}
	default:
		err = &NotSingularError{interfaceresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *InterfaceResultQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InterfaceResults.
func (_q *InterfaceResultQuery) All(ctx context.Context) ([]*InterfaceResult, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InterfaceResult, *InterfaceResultQuery]()
	return withInterceptors[[]*InterfaceResult](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *InterfaceResultQuery) AllX(ctx context.Context) []*InterfaceResult {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InterfaceResult IDs.
func (_q *InterfaceResultQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(interfaceresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *InterfaceResultQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *InterfaceResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*InterfaceResultQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *InterfaceResultQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *InterfaceResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *InterfaceResultQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InterfaceResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *InterfaceResultQuery) Clone() *InterfaceResultQuery {
	if _q == nil {
		return nil
	}
	return &InterfaceResultQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]interfaceresult.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.InterfaceResult{}, _q.predicates...),
		withInterface: _q.withInterface.Clone(),
		withFields:    _q.withFields.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithInterface tells the query-builder to eager-load the nodes that are connected to
// the "interface" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InterfaceResultQuery) WithInterface(opts ...func(*APIQuery)) *InterfaceResultQuery {
	query := (&APIClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInterface = query
	return _q
}

// WithFields tells the query-builder to eager-load the nodes that are connected to
// the "fields" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InterfaceResultQuery) WithFields(opts ...func(*InterfaceFieldQuery)) *InterfaceResultQuery {
	query := (&InterfaceFieldClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFields = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InterfaceID int64 `json:"interface_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InterfaceResult.Query().
//		GroupBy(interfaceresult.FieldInterfaceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *InterfaceResultQuery) GroupBy(field string, fields ...string) *InterfaceResultGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InterfaceResultGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = interfaceresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InterfaceID int64 `json:"interface_id,omitempty"`
//	}
//
//	client.InterfaceResult.Query().
//		Select(interfaceresult.FieldInterfaceID).
//		Scan(ctx, &v)
func (_q *InterfaceResultQuery) Select(fields ...string) *InterfaceResultSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &InterfaceResultSelect{InterfaceResultQuery: _q}
	sbuild.label = interfaceresult.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InterfaceResultSelect configured with the given aggregations.
func (_q *InterfaceResultQuery) Aggregate(fns ...AggregateFunc) *InterfaceResultSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *InterfaceResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !interfaceresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *InterfaceResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InterfaceResult, error) {
	var (
		nodes       = []*InterfaceResult{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withInterface != nil,
			_q.withFields != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InterfaceResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InterfaceResult{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withInterface; query != nil {
		if err := _q.loadInterface(ctx, query, nodes, nil,
			func(n *InterfaceResult, e *API) { n.Edges.Interface = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFields; query != nil {
		if err := _q.loadFields(ctx, query, nodes,
			func(n *InterfaceResult) { n.Edges.Fields = []*InterfaceField{} },
			func(n *InterfaceResult, e *InterfaceField) { n.Edges.Fields = append(n.Edges.Fields, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *InterfaceResultQuery) loadInterface(ctx context.Context, query *APIQuery, nodes []*InterfaceResult, init func(*InterfaceResult), assign func(*InterfaceResult, *API)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*InterfaceResult)
	for i := range nodes {
		fk := nodes[i].InterfaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(api.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "interface_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *InterfaceResultQuery) loadFields(ctx context.Context, query *InterfaceFieldQuery, nodes []*InterfaceResult, init func(*InterfaceResult), assign func(*InterfaceResult, *InterfaceField)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*InterfaceResult)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(interfacefield.FieldResultID)
	}
	query.Where(predicate.InterfaceField(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(interfaceresult.FieldsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ResultID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "result_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *InterfaceResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *InterfaceResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(interfaceresult.Table, interfaceresult.Columns, sqlgraph.NewFieldSpec(interfaceresult.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, interfaceresult.FieldID)
		for i := range fields {
			if fields[i] != interfaceresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withInterface != nil {
			_spec.Node.AddColumnOnce(interfaceresult.FieldInterfaceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *InterfaceResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(interfaceresult.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = interfaceresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InterfaceResultGroupBy is the group-by builder for InterfaceResult entities.
type InterfaceResultGroupBy struct {
	selector
	build *InterfaceResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *InterfaceResultGroupBy) Aggregate(fns ...AggregateFunc) *InterfaceResultGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *InterfaceResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InterfaceResultQuery, *InterfaceResultGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *InterfaceResultGroupBy) sqlScan(ctx context.Context, root *InterfaceResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InterfaceResultSelect is the builder for selecting fields of InterfaceResult entities.
type InterfaceResultSelect struct {
	*InterfaceResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *InterfaceResultSelect) Aggregate(fns ...AggregateFunc) *InterfaceResultSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *InterfaceResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InterfaceResultQuery, *InterfaceResultSelect](ctx, _s.InterfaceResultQuery, _s, _s.inters, v)
}

func (_s *InterfaceResultSelect) sqlScan(ctx context.Context, root *InterfaceResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
