// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nest-api/internal/ent/api"
	"nest-api/internal/ent/interfacequeryparam"
	"nest-api/internal/utils"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InterfaceQueryParam is the model entity for the InterfaceQueryParam schema.
type InterfaceQueryParam struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID int64 `json:"id,omitempty"`
	// 接口 ID
	InterfaceID int64 `json:"interface_id,omitempty"`
	// 参数名
	Name string `json:"name,omitempty"`
	// 类型
	Type string `json:"type,omitempty"`
	// 是否必填
	Required bool `json:"required,omitempty"`
	// 说明
	Description string `json:"description,omitempty"`
	// 参数示例
	Example string `json:"example,omitempty"`
	// 排序
	SortOrder int `json:"sort_order,omitempty"`
	// 创建时间
	CreatedAt utils.DateTime `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt utils.DateTime `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *utils.DateTime `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InterfaceQueryParamQuery when eager-loading is set.
	Edges        InterfaceQueryParamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InterfaceQueryParamEdges holds the relations/edges for other nodes in the graph.
type InterfaceQueryParamEdges struct {
	// Interface holds the value of the interface edge.
	Interface *API `json:"interface,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InterfaceOrErr returns the Interface value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InterfaceQueryParamEdges) InterfaceOrErr() (*API, error) {
	if e.Interface != nil {
		return e.Interface, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: api.Label}
	}
	return nil, &NotLoadedError{edge: "interface"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InterfaceQueryParam) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case interfacequeryparam.FieldDeletedAt:
			values[i] = &sql.NullScanner{S: new(utils.DateTime)}
		case interfacequeryparam.FieldRequired:
			values[i] = new(sql.NullBool)
		case interfacequeryparam.FieldID, interfacequeryparam.FieldInterfaceID, interfacequeryparam.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case interfacequeryparam.FieldName, interfacequeryparam.FieldType, interfacequeryparam.FieldDescription, interfacequeryparam.FieldExample:
			values[i] = new(sql.NullString)
		case interfacequeryparam.FieldCreatedAt, interfacequeryparam.FieldUpdatedAt:
			values[i] = new(utils.DateTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InterfaceQueryParam fields.
func (_m *InterfaceQueryParam) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case interfacequeryparam.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case interfacequeryparam.FieldInterfaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interface_id", values[i])
			} else if value.Valid {
				_m.InterfaceID = value.Int64
			}
		case interfacequeryparam.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case interfacequeryparam.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case interfacequeryparam.FieldRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field required", values[i])
			} else if value.Valid {
				_m.Required = value.Bool
			}
		case interfacequeryparam.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case interfacequeryparam.FieldExample:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field example", values[i])
			} else if value.Valid {
				_m.Example = value.String
			}
		case interfacequeryparam.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case interfacequeryparam.FieldCreatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil {
				_m.CreatedAt = *value
			}
		case interfacequeryparam.FieldUpdatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value != nil {
				_m.UpdatedAt = *value
			}
		case interfacequeryparam.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(utils.DateTime)
				*_m.DeletedAt = *value.S.(*utils.DateTime)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InterfaceQueryParam.
// This includes values selected through modifiers, order, etc.
func (_m *InterfaceQueryParam) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInterface queries the "interface" edge of the InterfaceQueryParam entity.
func (_m *InterfaceQueryParam) QueryInterface() *APIQuery {
	return NewInterfaceQueryParamClient(_m.config).QueryInterface(_m)
}

// Update returns a builder for updating this InterfaceQueryParam.
// Note that you need to call InterfaceQueryParam.Unwrap() before calling this method if this InterfaceQueryParam
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InterfaceQueryParam) Update() *InterfaceQueryParamUpdateOne {
	return NewInterfaceQueryParamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InterfaceQueryParam entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InterfaceQueryParam) Unwrap() *InterfaceQueryParam {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InterfaceQueryParam is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InterfaceQueryParam) String() string {
	var builder strings.Builder
	builder.WriteString("InterfaceQueryParam(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("interface_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InterfaceID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("required=")
	builder.WriteString(fmt.Sprintf("%v", _m.Required))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("example=")
	builder.WriteString(_m.Example)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InterfaceQueryParams is a parsable slice of InterfaceQueryParam.
type InterfaceQueryParams []*InterfaceQueryParam
