// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nest-api/internal/ent/api"
	"nest-api/internal/ent/interfacequeryparam"
	"nest-api/internal/ent/predicate"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InterfaceQueryParamUpdate is the builder for updating InterfaceQueryParam entities.
type InterfaceQueryParamUpdate struct {
	config
	hooks    []Hook
	mutation *InterfaceQueryParamMutation
}

// Where appends a list predicates to the InterfaceQueryParamUpdate builder.
func (_u *InterfaceQueryParamUpdate) Where(ps ...predicate.InterfaceQueryParam) *InterfaceQueryParamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInterfaceID sets the "interface_id" field.
func (_u *InterfaceQueryParamUpdate) SetInterfaceID(v int64) *InterfaceQueryParamUpdate {
	_u.mutation.SetInterfaceID(v)
	return _u
}

// SetNillableInterfaceID sets the "interface_id" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableInterfaceID(v *int64) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetInterfaceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *InterfaceQueryParamUpdate) SetName(v string) *InterfaceQueryParamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableName(v *string) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *InterfaceQueryParamUpdate) SetType(v string) *InterfaceQueryParamUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableType(v *string) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRequired sets the "required" field.
func (_u *InterfaceQueryParamUpdate) SetRequired(v bool) *InterfaceQueryParamUpdate {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableRequired(v *bool) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *InterfaceQueryParamUpdate) SetDescription(v string) *InterfaceQueryParamUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableDescription(v *string) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetExample sets the "example" field.
func (_u *InterfaceQueryParamUpdate) SetExample(v string) *InterfaceQueryParamUpdate {
	_u.mutation.SetExample(v)
	return _u
}

// SetNillableExample sets the "example" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableExample(v *string) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetExample(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *InterfaceQueryParamUpdate) SetSortOrder(v int) *InterfaceQueryParamUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableSortOrder(v *int) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *InterfaceQueryParamUpdate) AddSortOrder(v int) *InterfaceQueryParamUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InterfaceQueryParamUpdate) SetCreatedAt(v utils.DateTime) *InterfaceQueryParamUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableCreatedAt(v *utils.DateTime) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InterfaceQueryParamUpdate) SetUpdatedAt(v utils.DateTime) *InterfaceQueryParamUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InterfaceQueryParamUpdate) SetDeletedAt(v utils.DateTime) *InterfaceQueryParamUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdate) SetNillableDeletedAt(v *utils.DateTime) *InterfaceQueryParamUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InterfaceQueryParamUpdate) ClearDeletedAt() *InterfaceQueryParamUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetInterface sets the "interface" edge to the API entity.
func (_u *InterfaceQueryParamUpdate) SetInterface(v *API) *InterfaceQueryParamUpdate {
	return _u.SetInterfaceID(v.ID)
}

// Mutation returns the InterfaceQueryParamMutation object of the builder.
func (_u *InterfaceQueryParamUpdate) Mutation() *InterfaceQueryParamMutation {
	return _u.mutation
}

// ClearInterface clears the "interface" edge to the API entity.
func (_u *InterfaceQueryParamUpdate) ClearInterface() *InterfaceQueryParamUpdate {
	_u.mutation.ClearInterface()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InterfaceQueryParamUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InterfaceQueryParamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InterfaceQueryParamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InterfaceQueryParamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InterfaceQueryParamUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if interfacequeryparam.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized interfacequeryparam.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := interfacequeryparam.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InterfaceQueryParamUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := interfacequeryparam.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := interfacequeryparam.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := interfacequeryparam.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Example(); ok {
		if err := interfacequeryparam.ExampleValidator(v); err != nil {
			return &ValidationError{Name: "example", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.example": %w`, err)}
		}
	}
	if _u.mutation.InterfaceCleared() && len(_u.mutation.InterfaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InterfaceQueryParam.interface"`)
	}
	return nil
}

func (_u *InterfaceQueryParamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(interfacequeryparam.Table, interfacequeryparam.Columns, sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(interfacequeryparam.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(interfacequeryparam.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(interfacequeryparam.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(interfacequeryparam.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Example(); ok {
		_spec.SetField(interfacequeryparam.FieldExample, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(interfacequeryparam.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(interfacequeryparam.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(interfacequeryparam.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(interfacequeryparam.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(interfacequeryparam.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(interfacequeryparam.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.InterfaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   interfacequeryparam.InterfaceTable,
			Columns: []string{interfacequeryparam.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   interfacequeryparam.InterfaceTable,
			Columns: []string{interfacequeryparam.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interfacequeryparam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InterfaceQueryParamUpdateOne is the builder for updating a single InterfaceQueryParam entity.
type InterfaceQueryParamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InterfaceQueryParamMutation
}

// SetInterfaceID sets the "interface_id" field.
func (_u *InterfaceQueryParamUpdateOne) SetInterfaceID(v int64) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetInterfaceID(v)
	return _u
}

// SetNillableInterfaceID sets the "interface_id" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableInterfaceID(v *int64) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetInterfaceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *InterfaceQueryParamUpdateOne) SetName(v string) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableName(v *string) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *InterfaceQueryParamUpdateOne) SetType(v string) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableType(v *string) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRequired sets the "required" field.
func (_u *InterfaceQueryParamUpdateOne) SetRequired(v bool) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableRequired(v *bool) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *InterfaceQueryParamUpdateOne) SetDescription(v string) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableDescription(v *string) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetExample sets the "example" field.
func (_u *InterfaceQueryParamUpdateOne) SetExample(v string) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetExample(v)
	return _u
}

// SetNillableExample sets the "example" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableExample(v *string) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetExample(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *InterfaceQueryParamUpdateOne) SetSortOrder(v int) *InterfaceQueryParamUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableSortOrder(v *int) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *InterfaceQueryParamUpdateOne) AddSortOrder(v int) *InterfaceQueryParamUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InterfaceQueryParamUpdateOne) SetCreatedAt(v utils.DateTime) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableCreatedAt(v *utils.DateTime) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InterfaceQueryParamUpdateOne) SetUpdatedAt(v utils.DateTime) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InterfaceQueryParamUpdateOne) SetDeletedAt(v utils.DateTime) *InterfaceQueryParamUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InterfaceQueryParamUpdateOne) SetNillableDeletedAt(v *utils.DateTime) *InterfaceQueryParamUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InterfaceQueryParamUpdateOne) ClearDeletedAt() *InterfaceQueryParamUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetInterface sets the "interface" edge to the API entity.
func (_u *InterfaceQueryParamUpdateOne) SetInterface(v *API) *InterfaceQueryParamUpdateOne {
	return _u.SetInterfaceID(v.ID)
}

// Mutation returns the InterfaceQueryParamMutation object of the builder.
func (_u *InterfaceQueryParamUpdateOne) Mutation() *InterfaceQueryParamMutation {
	return _u.mutation
}

// ClearInterface clears the "interface" edge to the API entity.
func (_u *InterfaceQueryParamUpdateOne) ClearInterface() *InterfaceQueryParamUpdateOne {
	_u.mutation.ClearInterface()
	return _u
}

// Where appends a list predicates to the InterfaceQueryParamUpdate builder.
func (_u *InterfaceQueryParamUpdateOne) Where(ps ...predicate.InterfaceQueryParam) *InterfaceQueryParamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InterfaceQueryParamUpdateOne) Select(field string, fields ...string) *InterfaceQueryParamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InterfaceQueryParam entity.
func (_u *InterfaceQueryParamUpdateOne) Save(ctx context.Context) (*InterfaceQueryParam, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InterfaceQueryParamUpdateOne) SaveX(ctx context.Context) *InterfaceQueryParam {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InterfaceQueryParamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InterfaceQueryParamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InterfaceQueryParamUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if interfacequeryparam.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized interfacequeryparam.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := interfacequeryparam.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InterfaceQueryParamUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := interfacequeryparam.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := interfacequeryparam.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := interfacequeryparam.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Example(); ok {
		if err := interfacequeryparam.ExampleValidator(v); err != nil {
			return &ValidationError{Name: "example", err: fmt.Errorf(`ent: validator failed for field "InterfaceQueryParam.example": %w`, err)}
		}
	}
	if _u.mutation.InterfaceCleared() && len(_u.mutation.InterfaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InterfaceQueryParam.interface"`)
	}
	return nil
}

func (_u *InterfaceQueryParamUpdateOne) sqlSave(ctx context.Context) (_node *InterfaceQueryParam, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(interfacequeryparam.Table, interfacequeryparam.Columns, sqlgraph.NewFieldSpec(interfacequeryparam.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InterfaceQueryParam.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, interfacequeryparam.FieldID)
		for _, f := range fields {
			if !interfacequeryparam.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != interfacequeryparam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(interfacequeryparam.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(interfacequeryparam.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(interfacequeryparam.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(interfacequeryparam.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Example(); ok {
		_spec.SetField(interfacequeryparam.FieldExample, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(interfacequeryparam.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(interfacequeryparam.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(interfacequeryparam.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(interfacequeryparam.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(interfacequeryparam.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(interfacequeryparam.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.InterfaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   interfacequeryparam.InterfaceTable,
			Columns: []string{interfacequeryparam.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   interfacequeryparam.InterfaceTable,
			Columns: []string{interfacequeryparam.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InterfaceQueryParam{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interfacequeryparam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
