// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nest-api/internal/ent/api"
	"nest-api/internal/ent/projectshare"
	"nest-api/internal/ent/projectshareinterface"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectShareInterfaceCreate is the builder for creating a ProjectShareInterface entity.
type ProjectShareInterfaceCreate struct {
	config
	mutation *ProjectShareInterfaceMutation
	hooks    []Hook
}

// SetShareID sets the "share_id" field.
func (_c *ProjectShareInterfaceCreate) SetShareID(v int64) *ProjectShareInterfaceCreate {
	_c.mutation.SetShareID(v)
	return _c
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (_c *ProjectShareInterfaceCreate) SetNillableShareID(v *int64) *ProjectShareInterfaceCreate {
	if v != nil {
		_c.SetShareID(*v)
	}
	return _c
}

// SetInterfaceID sets the "interface_id" field.
func (_c *ProjectShareInterfaceCreate) SetInterfaceID(v int64) *ProjectShareInterfaceCreate {
	_c.mutation.SetInterfaceID(v)
	return _c
}

// SetNillableInterfaceID sets the "interface_id" field if the given value is not nil.
func (_c *ProjectShareInterfaceCreate) SetNillableInterfaceID(v *int64) *ProjectShareInterfaceCreate {
	if v != nil {
		_c.SetInterfaceID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectShareInterfaceCreate) SetCreatedAt(v utils.DateTime) *ProjectShareInterfaceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectShareInterfaceCreate) SetNillableCreatedAt(v *utils.DateTime) *ProjectShareInterfaceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectShareInterfaceCreate) SetID(v int64) *ProjectShareInterfaceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetShare sets the "share" edge to the ProjectShare entity.
func (_c *ProjectShareInterfaceCreate) SetShare(v *ProjectShare) *ProjectShareInterfaceCreate {
	return _c.SetShareID(v.ID)
}

// SetInterface sets the "interface" edge to the API entity.
func (_c *ProjectShareInterfaceCreate) SetInterface(v *API) *ProjectShareInterfaceCreate {
	return _c.SetInterfaceID(v.ID)
}

// Mutation returns the ProjectShareInterfaceMutation object of the builder.
func (_c *ProjectShareInterfaceCreate) Mutation() *ProjectShareInterfaceMutation {
	return _c.mutation
}

// Save creates the ProjectShareInterface in the database.
func (_c *ProjectShareInterfaceCreate) Save(ctx context.Context) (*ProjectShareInterface, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectShareInterfaceCreate) SaveX(ctx context.Context) *ProjectShareInterface {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectShareInterfaceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectShareInterfaceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectShareInterfaceCreate) defaults() {
	if _, ok := _c.mutation.ShareID(); !ok {
		v := projectshareinterface.DefaultShareID
		_c.mutation.SetShareID(v)
	}
	if _, ok := _c.mutation.InterfaceID(); !ok {
		v := projectshareinterface.DefaultInterfaceID
		_c.mutation.SetInterfaceID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectshareinterface.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectShareInterfaceCreate) check() error {
	if _, ok := _c.mutation.ShareID(); !ok {
		return &ValidationError{Name: "share_id", err: errors.New(`ent: missing required field "ProjectShareInterface.share_id"`)}
	}
	if _, ok := _c.mutation.InterfaceID(); !ok {
		return &ValidationError{Name: "interface_id", err: errors.New(`ent: missing required field "ProjectShareInterface.interface_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectShareInterface.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := projectshareinterface.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProjectShareInterface.id": %w`, err)}
		}
	}
	if len(_c.mutation.ShareIDs()) == 0 {
		return &ValidationError{Name: "share", err: errors.New(`ent: missing required edge "ProjectShareInterface.share"`)}
	}
	if len(_c.mutation.InterfaceIDs()) == 0 {
		return &ValidationError{Name: "interface", err: errors.New(`ent: missing required edge "ProjectShareInterface.interface"`)}
	}
	return nil
}

func (_c *ProjectShareInterfaceCreate) sqlSave(ctx context.Context) (*ProjectShareInterface, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectShareInterfaceCreate) createSpec() (*ProjectShareInterface, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectShareInterface{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectshareinterface.Table, sqlgraph.NewFieldSpec(projectshareinterface.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectshareinterface.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectshareinterface.ShareTable,
			Columns: []string{projectshareinterface.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectshare.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShareID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectshareinterface.InterfaceTable,
			Columns: []string{projectshareinterface.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InterfaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectShareInterfaceCreateBulk is the builder for creating many ProjectShareInterface entities in bulk.
type ProjectShareInterfaceCreateBulk struct {
	config
	err      error
	builders []*ProjectShareInterfaceCreate
}

// Save creates the ProjectShareInterface entities in the database.
func (_c *ProjectShareInterfaceCreateBulk) Save(ctx context.Context) ([]*ProjectShareInterface, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectShareInterface, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectShareInterfaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectShareInterfaceCreateBulk) SaveX(ctx context.Context) []*ProjectShareInterface {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectShareInterfaceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectShareInterfaceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
