// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nest-api/internal/ent/project"
	"nest-api/internal/ent/user"
	"nest-api/internal/ent/workspace"
	"nest-api/internal/utils"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID int64 `json:"id,omitempty"`
	// 工作空间 ID
	WorkspaceID int64 `json:"workspace_id,omitempty"`
	// 项目名称
	Name string `json:"name,omitempty"`
	// 创建者用户 ID
	CreatedBy int64 `json:"created_by,omitempty"`
	// 创建时间
	CreatedAt utils.DateTime `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt utils.DateTime `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *utils.DateTime `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Folders holds the value of the folders edge.
	Folders []*Folder `json:"folders,omitempty"`
	// Interfaces holds the value of the interfaces edge.
	Interfaces []*API `json:"interfaces,omitempty"`
	// Environments holds the value of the environments edge.
	Environments []*Environment `json:"environments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// FoldersOrErr returns the Folders value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) FoldersOrErr() ([]*Folder, error) {
	if e.loadedTypes[2] {
		return e.Folders, nil
	}
	return nil, &NotLoadedError{edge: "folders"}
}

// InterfacesOrErr returns the Interfaces value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) InterfacesOrErr() ([]*API, error) {
	if e.loadedTypes[3] {
		return e.Interfaces, nil
	}
	return nil, &NotLoadedError{edge: "interfaces"}
}

// EnvironmentsOrErr returns the Environments value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) EnvironmentsOrErr() ([]*Environment, error) {
	if e.loadedTypes[4] {
		return e.Environments, nil
	}
	return nil, &NotLoadedError{edge: "environments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldDeletedAt:
			values[i] = &sql.NullScanner{S: new(utils.DateTime)}
		case project.FieldID, project.FieldWorkspaceID, project.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case project.FieldName:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldUpdatedAt:
			values[i] = new(utils.DateTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case project.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = value.Int64
			}
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value != nil {
				_m.CreatedAt = *value
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*utils.DateTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value != nil {
				_m.UpdatedAt = *value
			}
		case project.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(utils.DateTime)
				*_m.DeletedAt = *value.S.(*utils.DateTime)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkspace queries the "workspace" edge of the Project entity.
func (_m *Project) QueryWorkspace() *WorkspaceQuery {
	return NewProjectClient(_m.config).QueryWorkspace(_m)
}

// QueryCreator queries the "creator" edge of the Project entity.
func (_m *Project) QueryCreator() *UserQuery {
	return NewProjectClient(_m.config).QueryCreator(_m)
}

// QueryFolders queries the "folders" edge of the Project entity.
func (_m *Project) QueryFolders() *FolderQuery {
	return NewProjectClient(_m.config).QueryFolders(_m)
}

// QueryInterfaces queries the "interfaces" edge of the Project entity.
func (_m *Project) QueryInterfaces() *APIQuery {
	return NewProjectClient(_m.config).QueryInterfaces(_m)
}

// QueryEnvironments queries the "environments" edge of the Project entity.
func (_m *Project) QueryEnvironments() *EnvironmentQuery {
	return NewProjectClient(_m.config).QueryEnvironments(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
