// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nest-api/internal/ent/predicate"
	"nest-api/internal/ent/workspacemember"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceMemberDelete is the builder for deleting a WorkspaceMember entity.
type WorkspaceMemberDelete struct {
	config
	hooks    []Hook
	mutation *WorkspaceMemberMutation
}

// Where appends a list predicates to the WorkspaceMemberDelete builder.
func (_d *WorkspaceMemberDelete) Where(ps ...predicate.WorkspaceMember) *WorkspaceMemberDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WorkspaceMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceMemberDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WorkspaceMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workspacemember.Table, sqlgraph.NewFieldSpec(workspacemember.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WorkspaceMemberDeleteOne is the builder for deleting a single WorkspaceMember entity.
type WorkspaceMemberDeleteOne struct {
	_d *WorkspaceMemberDelete
}

// Where appends a list predicates to the WorkspaceMemberDelete builder.
func (_d *WorkspaceMemberDeleteOne) Where(ps ...predicate.WorkspaceMember) *WorkspaceMemberDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WorkspaceMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workspacemember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceMemberDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
