// Code generated by ent, DO NOT EDIT.

package interfacerequestheader

import (
	"nest-api/internal/ent/predicate"
	"nest-api/internal/utils"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldID, id))
}

// InterfaceID applies equality check predicate on the "interface_id" field. It's identical to InterfaceIDEQ.
func InterfaceID(v int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldInterfaceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldType, v))
}

// Required applies equality check predicate on the "required" field. It's identical to RequiredEQ.
func Required(v bool) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldRequired, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldDescription, v))
}

// Example applies equality check predicate on the "example" field. It's identical to ExampleEQ.
func Example(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldExample, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldDeletedAt, v))
}

// InterfaceIDEQ applies the EQ predicate on the "interface_id" field.
func InterfaceIDEQ(v int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldInterfaceID, v))
}

// InterfaceIDNEQ applies the NEQ predicate on the "interface_id" field.
func InterfaceIDNEQ(v int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldInterfaceID, v))
}

// InterfaceIDIn applies the In predicate on the "interface_id" field.
func InterfaceIDIn(vs ...int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldInterfaceID, vs...))
}

// InterfaceIDNotIn applies the NotIn predicate on the "interface_id" field.
func InterfaceIDNotIn(vs ...int64) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldInterfaceID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContainsFold(FieldType, v))
}

// RequiredEQ applies the EQ predicate on the "required" field.
func RequiredEQ(v bool) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldRequired, v))
}

// RequiredNEQ applies the NEQ predicate on the "required" field.
func RequiredNEQ(v bool) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldRequired, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContainsFold(FieldDescription, v))
}

// ExampleEQ applies the EQ predicate on the "example" field.
func ExampleEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldExample, v))
}

// ExampleNEQ applies the NEQ predicate on the "example" field.
func ExampleNEQ(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldExample, v))
}

// ExampleIn applies the In predicate on the "example" field.
func ExampleIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldExample, vs...))
}

// ExampleNotIn applies the NotIn predicate on the "example" field.
func ExampleNotIn(vs ...string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldExample, vs...))
}

// ExampleGT applies the GT predicate on the "example" field.
func ExampleGT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldExample, v))
}

// ExampleGTE applies the GTE predicate on the "example" field.
func ExampleGTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldExample, v))
}

// ExampleLT applies the LT predicate on the "example" field.
func ExampleLT(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldExample, v))
}

// ExampleLTE applies the LTE predicate on the "example" field.
func ExampleLTE(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldExample, v))
}

// ExampleContains applies the Contains predicate on the "example" field.
func ExampleContains(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContains(FieldExample, v))
}

// ExampleHasPrefix applies the HasPrefix predicate on the "example" field.
func ExampleHasPrefix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasPrefix(FieldExample, v))
}

// ExampleHasSuffix applies the HasSuffix predicate on the "example" field.
func ExampleHasSuffix(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldHasSuffix(FieldExample, v))
}

// ExampleEqualFold applies the EqualFold predicate on the "example" field.
func ExampleEqualFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEqualFold(FieldExample, v))
}

// ExampleContainsFold applies the ContainsFold predicate on the "example" field.
func ExampleContainsFold(v string) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldContainsFold(FieldExample, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v utils.DateTime) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.FieldNotNull(FieldDeletedAt))
}

// HasInterface applies the HasEdge predicate on the "interface" edge.
func HasInterface() predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InterfaceTable, InterfaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInterfaceWith applies the HasEdge predicate on the "interface" edge with a given conditions (other predicates).
func HasInterfaceWith(preds ...predicate.API) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(func(s *sql.Selector) {
		step := newInterfaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InterfaceRequestHeader) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InterfaceRequestHeader) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InterfaceRequestHeader) predicate.InterfaceRequestHeader {
	return predicate.InterfaceRequestHeader(sql.NotPredicates(p))
}
